### ISSUE TITLE
Typos in About

### ISSUE THREAD

**Issue by yuderekyu** [Ragnyll/ragnyll.github.io#1]
Some typos in the `about` section:

* ...how any **computer** I use should work...
* ...If you **don't** like that, then get the hell out.
* That being said, I do welcome **criticism** and corrections with **anything** I may post.

I'm also a big proponent on not keeping writing and talking one-to-one. There are areas where we can be concise. For example:
> I also really just _do not care_ about front end design.

can be

> Also, I _do not care_ about front end design.

**Comment by Ragnyll** [comment]
a0562e4ec286015a2f4ee884d882fbf2d89a5a0b
Thanks Derek.
